import type { Metadata } from "next";
import { siteUrl } from "@/lib/env";
import { BRAND } from "./jsonld";

/**
 * One place that builds page metadata, so every page gets a canonical, an OG
 * card and a Twitter card without each route remembering to.
 *
 * `path` is always site-relative; canonicals are absolute by construction.
 */
/**
 * The share card a page falls back to when it has none of its own. Generated by
 * `scripts/build-og-default.mjs` and checked in.
 *
 * Deliberately reached only through this function. The guest invitation builds
 * its own metadata and withholds `og:image` while watermarked — that absence is
 * the paywall — so the default must never arrive there by inheritance. That is
 * also why this is not an `app/opengraph-image` file: Next would hand it down
 * the whole route tree, `/invite/[slug]` included.
 */
const DEFAULT_OG_IMAGE = "/assets/og-default.png";

export function pageMetadata(input: {
  title: string;
  description: string;
  path: string;
  /** Site-relative OG image. Falls back to the shared default card. */
  image?: string;
  imageAlt?: string;
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
  tags?: string[];
  /** Paginated and filtered listings past page 1 stay out of the index. */
  noIndex?: boolean;
  /** Rel prev/next for paginated listings. */
  prev?: string;
  next?: string;
}): Metadata {
  const url = new URL(input.path, siteUrl).toString();
  const image = new URL(input.image ?? DEFAULT_OG_IMAGE, siteUrl).toString();
  const imageAlt = input.image
    ? (input.imageAlt ?? input.title)
    : "The Amantrika torana mark above the wordmark — digital invitations for Indian celebrations";

  return {
    title: input.title,
    description: input.description,
    alternates: { canonical: url },
    robots: input.noIndex
      ? { index: false, follow: true }
      : { index: true, follow: true, googleBot: { index: true, follow: true } },
    openGraph: {
      type: input.type ?? "website",
      url,
      title: input.title,
      description: input.description,
      siteName: BRAND.name,
      locale: "en_IN",
      images: [{ url: image, alt: imageAlt }],
      ...(input.type === "article"
        ? {
            publishedTime: input.publishedTime,
            modifiedTime: input.modifiedTime ?? input.publishedTime,
            authors: input.authors,
            tags: input.tags,
          }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description: input.description,
      images: [image],
    },
    ...(input.prev || input.next
      ? {
          other: {
            ...(input.prev ? { "link:prev": new URL(input.prev, siteUrl).toString() } : {}),
            ...(input.next ? { "link:next": new URL(input.next, siteUrl).toString() } : {}),
          },
        }
      : {}),
  };
}
