// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/admin" | "/admin/invitations" | "/admin/partners" | "/admin/plans" | "/admin/showcase" | "/admin/users" | "/agent" | "/blog" | "/blog/[slug]" | "/blog/category/[category]" | "/blog/category/[category]/page/[page]" | "/blog/page/[page]" | "/blog/tag/[tag]" | "/blog/tag/[tag]/page/[page]" | "/checkout/mock/[orderId]" | "/dashboard" | "/dashboard/[id]" | "/design-system" | "/design-system/borders" | "/design-system/components" | "/design-system/components/[slug]" | "/design-system/icons" | "/design-system/motion" | "/design-system/openings" | "/design-system/patterns" | "/design-system/textures" | "/design-system/themes" | "/design-system/tokens" | "/invite/[slug]" | "/login" | "/onboarding" | "/showcase" | "/showcase/[slug]" | "/signup"
type AppRouteHandlerRoutes = "/api/payments/webhook" | "/api/track" | "/auth/callback" | "/blog/rss.xml" | "/llms-full.txt" | "/llms.txt" | "/md/[...slug]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/design-system"
type RedirectRoutes = never
type RewriteRoutes = "/ingest/[[...path]]" | "/ingest/static/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/admin": {}
  "/admin/invitations": {}
  "/admin/partners": {}
  "/admin/plans": {}
  "/admin/showcase": {}
  "/admin/users": {}
  "/agent": {}
  "/api/payments/webhook": {}
  "/api/track": {}
  "/auth/callback": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/category/[category]": { "category": string; }
  "/blog/category/[category]/page/[page]": { "category": string; "page": string; }
  "/blog/page/[page]": { "page": string; }
  "/blog/rss.xml": {}
  "/blog/tag/[tag]": { "tag": string; }
  "/blog/tag/[tag]/page/[page]": { "tag": string; "page": string; }
  "/checkout/mock/[orderId]": { "orderId": string; }
  "/dashboard": {}
  "/dashboard/[id]": { "id": string; }
  "/design-system": {}
  "/design-system/borders": {}
  "/design-system/components": {}
  "/design-system/components/[slug]": { "slug": string; }
  "/design-system/icons": {}
  "/design-system/motion": {}
  "/design-system/openings": {}
  "/design-system/patterns": {}
  "/design-system/textures": {}
  "/design-system/themes": {}
  "/design-system/tokens": {}
  "/ingest/[[...path]]": { "path"?: string[]; }
  "/ingest/static/[[...path]]": { "path"?: string[]; }
  "/invite/[slug]": { "slug": string; }
  "/llms-full.txt": {}
  "/llms.txt": {}
  "/login": {}
  "/md/[...slug]": { "slug": string[]; }
  "/onboarding": {}
  "/showcase": {}
  "/showcase/[slug]": { "slug": string; }
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/design-system": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
