// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/admin/invitations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invitations">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/invitations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/partners">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plans">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/showcase">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/dashboard/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/blog/category/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/category/[category]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/blog/category/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/blog/category/[category]/page/[page]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/category/[category]/page/[page]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/blog/category/[category]/page/[page]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/blog/page/[page]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/page/[page]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/blog/page/[page]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/blog/tag/[tag]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/tag/[tag]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/blog/tag/[tag]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/blog/tag/[tag]/page/[page]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/tag/[tag]/page/[page]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/blog/tag/[tag]/page/[page]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/showcase/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/showcase/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/showcase/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/showcase">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/mock/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/mock/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/mock/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/borders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/borders">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/borders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/components/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/components/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/components/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/components/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/components">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/components/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/icons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/icons">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/icons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/motion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/motion">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/motion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/openings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/openings">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/openings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/patterns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/patterns">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/patterns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/textures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/textures">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/textures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/themes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/themes">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/themes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/tokens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/tokens">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/tokens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/invite/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/blog/rss.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/blog/rss.xml">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/blog/rss.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track">> = Specific
  const handler = {} as typeof import("../../src/app/api/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/llms-full.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms-full.txt">> = Specific
  const handler = {} as typeof import("../../src/app/llms-full.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/llms.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms.txt">> = Specific
  const handler = {} as typeof import("../../src/app/llms.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/md/[...slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/md/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/md/[...slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/design-system">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
